### ISSUE TITLE
Illegal string offset in PHP7.1

### ISSUE THREAD

**Issue by FelixMalfait** [MindscapeHQ/raygun4php#90]
I'm getting the following error since Heroku upgraded its build pack to PHP 7.1.
Everything works fine after downgrading to 7.0.13

Uncaught ErrorException: Illegal string offset 'Total-Route-Time' in /app/vendor/mindscape/raygun4php/src/Raygun4php/RaygunRequestMessage.php:92 

```
Stack trace: 
#0 /app/vendor/mindscape/raygun4php/src/Raygun4php/RaygunRequestMessage.php(92): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Illegal string ...', '/app/vendor/min...', 92, Array) 
#1 /app/vendor/mindscape/raygun4php/src/Raygun4php/RaygunRequestMessage.php(35): Raygun4php\RaygunRequestMessage->emu_getAllHeaders() 
#2 /app/vendor/mindscape/raygun4php/src/Raygun4php/RaygunMessage.php(28): Raygun4php\RaygunRequestMessage->__construct() 
#3 /app/vendor/mindscape/raygun4php/src/Raygun4php/RaygunClient.php(234): Raygun4php\RaygunMessage->Build(Object(ErrorException)) 
#4 /app/vendor/mindscape/raygun4php/src/Raygun4php/RaygunClient.php(104): Raygun4php\RaygunClient->BuildMessage(Object(ErrorException), NULL) 
#5 /app/app/Core/Exceptions/Handler.php(59): Raygun4php\RaygunClient->SendException(Object(ErrorException)) 
#6 /app/bootstrap/cache/compil in /app/vendor/mindscape/raygun4php/src/Raygun4php/RaygunRequestMessage.php on line 92 
```

**Comment by BenjaminHarding** [comment]
Thanks for that @FelixMalfait. Planning to fix and release a patch version shortly.
